### ISSUE TITLE
Perl script does not include VCF entry unless PASS is in specific column

### ISSUE THREAD

**Issue by rffrancon** [iqbal-lab-org/gramtools#102]

**Comment by iqbal-lab** [comment]
I think this is correct behaviour btw - a VCF line needs PASS in the filter column to be valid. People stuff all kinds of shit into VCFs and mark the bad lines in that column

**Comment by rffrancon** [comment]
Is the following behavior correct?
* VCF filter column identified regardless of position.
* If filter column absent, include all entries.
* If filter column present, include entries which have PASS as filter column values.

I will modify the title.

**Comment by iqbal-lab** [comment]
Do you mean column absent or for a given row, if there is no entry?

**Comment by iqbal-lab** [comment]
Column is mandatory, my VCF (that triggered this) was malformed

**Comment by rffrancon** [comment]
I didn't realize that the filter column was mandatory. I've just consulted the VCF (v4.3) specs. I now see that the filter column is mandatory and that the columns ordering is fixed.

The perl script is correct and that VCF file was malformed. I'll close this issue.
