### ISSUE TITLE
kmer-size consistency between build and quasimap

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/gramtools#112]
I ran `build` using `--kmer-size 5`. Then with `quasimap`:
* using `--kmer-size 5` works fine and the reads get mapped
* not using `--kmer-size` results in zero reads mapped. `report.json` has `--kmer-size 15` in the command in `"gramtools_cpp_quasimap" -> "command"`.

Does `--kmer-size` even need to be an option to `quasimap`? Seems like it's specified when running `build`.

**Comment by rffrancon** [comment]
Will remove the `--kmer-size` option from quasimap. It used to be important to us when gramtools was in a different state.

**Comment by rffrancon** [comment]
Fix implemented here: f4655b7f47c1e15a236f15fc6d1cf3afcbd6c567
