### ISSUE TITLE
quasimap Assertion `index_end_boundary >= allele_coverage_offset' failed

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/gramtools#121]
gramtools version b05f148e0ecd522e6d1dc1affbc3b8798320091f

commands:
```
source /nfs/leia/research/iqbal/mhunt/Cryptic_releases/201805/Multi_sample/python_venv/bin/activate

gramtools quasimap --gram-directory /hps/nobackup/iqbal/mhunt/tmp/multi_sample.nextflow.work/76/55ee77e59995f90e862352526d38f0/small_vars_clustered.gramtools.build/split.27.gramtools_build --output-directory test.out --reads small_vars.minos.132/split.out/unmapped_reads.bam --reads small_vars.minos.132/split.out/split.27.reads.bam
```

Ran in here:
`/hps/nobackup/iqbal/mhunt/tmp/multi_sample.nextflow.work/ca/afe74136db866b6432211db8db35f1/`

See `test.sh.{o,e}` in that directory for stdout/err and LSF info

**Comment by rffrancon** [comment]
I can reproduce this locally (my laptop). Will debug.

**Comment by rffrancon** [comment]
I have a partial solution for this issue. I understand it completely. However, we need to readdress https://github.com/iqbal-lab-org/gramtools/issues/90 before I can proceed with certainty. I've left a comment on that issue to further enhance the spec.

**Comment by rffrancon** [comment]
@martinghunt @iqbal-lab This bug arises when a single read has multiple mappings which are encapsulated within different alleles.

Gramtools attempts to allocate PRG paths to mappings which are encapsulated within alleles. It failed to associate read mapping SA indexes with the correct alleles.

The solution has been merged into master here: https://github.com/iqbal-lab-org/gramtools/commit/e22cd4fbddadbbbb05ecc5bbe4fc91880eb128f5

Will tag this issue with `testing` and keep open for a week or two or until feedback is obtained.

**Comment by martinghunt** [comment]
Update: running on the same dataset that caused the error. All samples so far (~150 of 4000) ran ok, including the one above that had the error.

**Comment by martinghunt** [comment]
I'm sure it's fine. 4016/4034 ran OK. The nextflow job that was orchestrating all these gramtools runs got killed by LSF because it hit the run time limit before the remaining 18 could finish.
