### ISSUE TITLE
Clarify quasimap reported read count 

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#126]
The user expects

Count all reads:xxx

to have xxx=the number of reads in the input file

**Comment by rffrancon** [comment]
I've added a note to stdout which indicates that read reverse complements are also included in these counts.
Merged into master here: https://github.com/iqbal-lab-org/gramtools/commit/e440cc1529cef03e949791d1e1736fabca7ab82d

Please reopen if you'd like to see a different change.

**Comment by iqbal-lab** [comment]
I think this is ok with me
