### ISSUE TITLE
Rayan's suggestion to half the alphabet size

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#13]
get rid of the odd numbers and check start and end with ranks over the mask

**Comment by iqbal-lab** [comment]
Sorina, I propose we close this. We have a better solution planned.

**Comment by sm0179** [comment]
um, I don't think our solution applies to this. whatever way we choose to do the range search, we still need to check whether the markers found represent the start or end of a site

**Comment by iqbal-lab** [comment]
yes, but don't need one alphabet per site
