### ISSUE TITLE
Benchmarking TB: build and quasimap

### ISSUE THREAD

**Issue by rffrancon** [iqbal-lab-org/gramtools#132]
* SNPs and small indels above frequency 0.01.
* Combine the VCFs of 500 M. tuberculosis samples
* genotype those 500 samples at the duplicated site-list
* get a single VCF
* exclude SNP/indels below 1% frequency.

**Comment by bricoletc** [comment]
I'm closing this issue as we have demonstrated build and quasimap works on 3K (Kerri) and 50K (CRyPTIC) samples in TB, using [minos](https://github.com/iqbal-lab-org/minos/).

**Comment by iqbal-lab** [comment]
kerri''s 3k and the 50k dont ever build a whole genome prg with that many genomes do they?

**Comment by bricoletc** [comment]
true, we have found in both cases that the high amount of variation means we had to split the whole genome VCF for all samples and make and process PRGs of those splits.

In the future we will have such a TB variant dense dataset to benchmark changes to gramtools.
