### ISSUE TITLE
Discover command

### ISSUE THREAD

**Issue by rffrancon** [iqbal-lab-org/gramtools#134]
This command finds new variation with respect to an inferred personal reference.

#### Inputs
These are the inputs to this command:
* a gram directory (generated from a VCF `vcf_build` and a reference `reference_build`)
* an _inferred personal reference_ `vcf_infer` with `reference_build` as a reference (VCF format output of the `infer` command)
* a set of reads.

#### Procedure
The following is an outline of how this command works:
1. Construct a FASTA equivalent of `vcf_infer` called `reference_infer`. This is accomplished by selecting the alternative allele for each entry within `vcf_infer`.
1. `reference_infer` and reads are passed to cortex which generates a VCF. This VCF will be referred to as `vcf_cortex`.
2. A new VCF file is generated by transposing `vcf_cortex` such that the reference is `reference_build` instead of `reference_infer`. This VCF file will be referred to as `vcf_discover`. Using `vcf_infer` instead of `reference_infer` is necessary at this step.

#### Output
Discover produces a single VCF file as an output: `vcf_discover`. This VCF file uses `reference_build` as a reference.

#### Notes
Each entry within `vcf_cortex` can contain at most one alternative. Furthermore, these entries do not overlap. This should also hold true for `vcf_discover`.

**Comment by iqbal-lab** [comment]
This command finds new variation with respect to an inferred personal reference.

Inputs
These are the inputs to this command:

- a gram directory (generated from a VCF vcf_build and an original reference O-ref)
 -an inferred personal reference (output of the infer command; format: FASTA, abbrev P-ref)
 -a set of reads.

Procedure
The following is an outline of how this command works:

The inferred personal reference and reads are passed to cortex which generates a VCF. This VCF will be referred to as vcf_cortex.
vcf_cortex is then transformed/projected such that the reference is the same as that used by vcf_build (O-ref).

**Comment by rffrancon** [comment]
The `infer` command can generate either a VCF `vcf_infer` or FASTA `reference_infer` output. The `discover` command should take `vcf_infer` as an input and not `reference_infer`. This will make it easier to "rebase" the cortex output VCF `vcf_cortex` on to the reference found in the gram directory.

Will update top comment.

**Comment by iqbal-lab** [comment]
Cortex (or other caller) will need the reference_infer also.

**Comment by rffrancon** [comment]
implemented here: https://github.com/iqbal-lab-org/gramtools/commit/a9fa87815f052ae0ec808149323d4d3e50748e45
