### ISSUE TITLE
ISA sampling scheme

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#14]
not using the ISA in the new, implementation, so no need to store it

**Comment by rffrancon** [comment]
What does ISA mean? What is the ISA?

**Comment by sm0179** [comment]
inverse suffix array, sdsl builds it as part of our fm_index data structure, but we don't need it

**Comment by rffrancon** [comment]
@sm0179 what is the work that needs to be done in this issue? Do we need to modify the fm_index data structure so that the ISA is not built?
