### ISSUE TITLE
`left_markers_search` instruction bottleneck

### ISSUE THREAD

**Issue by bricoletc** [iqbal-lab-org/gramtools#141]
From profiling the cache instruction calls of `quasimap` in a7db53abc75b4ceb2d347337b1d3b6ec52ebe2a8 we see the following:

![callgrind_a7db53](https://user-images.githubusercontent.com/22122595/52940839-615e7200-335f-11e9-90e2-ef5311cd7b98.png)

\>50% of all instructions are spent in single function `left_markers_search`

Profiling using valgrind callgrind.

**Comment by bricoletc** [comment]
Here is the callgraph with %of all instructions for the same dataset (TB simulated dataset), having modified `left_markers_search`:

![perf_left_markers_tbdataset_callgrind](https://user-images.githubusercontent.com/22122595/52942717-67eee880-3363-11e9-8743-7900edbfc9d3.png)

We go down from a total of 1.94 trillion instructions to a total of 0.94 trillion instructions. This speeds up backward search, affecting both `build` and `quasimap`.

The speedup was independently confirmed by `quasimap` of some plasmodium reads against the pf3k/DBLMSP1+2 prg.

**Comment by iqbal-lab** [comment]
Awesome
