### ISSUE TITLE
Cortex dependency on stampy

### ISSUE THREAD

**Issue by bricoletc** [iqbal-lab-org/gramtools#150]
`gramtools discover` currently uses `cortex` which relies on `stampy` which is is python2.7.

This means that anyone that wants to install and use `gramtools` right now must have python2.
We currently  use https://github.com/iqbal-lab-org/py-cortex-api to install cortex and its dependencies. I don't want to put it up to Pypi yet because it has this 'hidden' python2 dependency.

@iqbal-lab what should we do about this?
Change cortex to not use stampy?
Translate the stampy code to python3?

**Comment by iqbal-lab** [comment]
totally happy to remove stampy from cortex and use bwa-mem for example. what would need to change?
1. change code to call bwa (perl scrips process_calls.pl would change)
2. change code which currently looks at SAM file, and parses the quality string, which stampy puts = in for every base where the query matches the reference in the mapped location, and instead use NM.
3/ change code which makes a stampy index of the reference to use bwa

**Comment by bricoletc** [comment]
@martinghunt if you have any mental energy for this

**Comment by bricoletc** [comment]
https://github.com/iqbal-lab/cortex/pull/27 implements this
