### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by bricoletc** [iqbal-lab-org/gramtools#154]
In this release we want a stable version of gramtools for use by [minos](https://github.com/iqbal-lab-org/minos). I propose b95321b. 

I ran a pipeline to compute Mendelian errors from Plasmodium crosses and found:

* 958fd53 : the commit that current latest minos uses

![MendErr_rate_all](https://user-images.githubusercontent.com/22122595/71813433-80e2b400-3071-11ea-92e8-62aed813210c.png)

* cf5cc20 : the version I propose using (minus 1 commit; b95321b adds a CLI bugfix). Main change is it uses a coverage graph to store and output per base coverage

![MendErr_rate_all](https://user-images.githubusercontent.com/22122595/71813423-788a7900-3071-11ea-8cb4-7dfe625ddd6c.png)

x-axis is filtering sites by increasing 5-percent quantiles of GT CONF. 

**We get the same Mend error rate with no filtering: 6.5 x 10e-04**

This is slightly higher than the analysis I ran in May using e66865e, at 5.0 x 10e-04. 

This could be due to code changes OR having then analysed 52 samples genome wide rather than 20 samples on chroms 1&2.

**Comment by bricoletc** [comment]
@iqbal-lab @martinghunt sound OK?

**Comment by iqbal-lab** [comment]
when you say "We get the same Mend error rate" - same as what?

**Comment by bricoletc** [comment]
between the two commits shown

**Comment by iqbal-lab** [comment]
ah i see, ok by me!

**Comment by martinghunt** [comment]
Looks good to me 👍
