### ISSUE TITLE
Boost download link is dead, breaks gramtools compilation process

### ISSUE THREAD

**Issue by bricoletc** [iqbal-lab-org/gramtools#158]
In libgramtools/lib/boost.cmake: `wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz --timestamping` now fails with a `403` error.

This has happened before: https://github.com/boostorg/boost/issues/403

Two options:
  - [Easy, short-term] Change target link; eg https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
  - [Better, mid-term] Use a package manager, eg hunter or conan, which can use potentially stabler/different links when downloading dependencies

Going for option 2.

**Comment by leoisl** [comment]
Just a complement, the download issue will not be solved, bintray has shut down: https://bintray.com/

**Comment by leoisl** [comment]
So, I think it would be nice to implement the easy solution 1 while you work on solution 2. Gramtools won't be installable until one of the solutions are implemented

**Comment by bricoletc** [comment]
Fair point thanks, I will push solution 1 first

**Comment by bricoletc** [comment]
v1.8.0 fixed this issue, implementing point 2 via Conan.
Added advantage is Conan ships prebuilt binaries, which can avoid compiling dependencies from source (eg boost).
