### ISSUE TITLE
Segfaults when it meets a read of all Ns

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#16]
Mapped 7G8 to a WG PRG, and by chance one read was all Ns.
Segfaulted
#11 0x0000000000440e8e in main (argc=12, argv=0x7fffffffbdb8) at ./map.cpp:91

(gdb) frame 11
#11 0x0000000000440e8e in main (argc=12, argv=0x7fffffffbdb8) at ./map.cpp:91

91                      std::vector<uint8_t> kmer(p.begin()+p.size()-k,p.end()); //is there a way to avoid making this copy?
(gdb) l
86                              if (q->seq[i]=='C' or q->seq[i]=='c') p.push_back(2);
87                              if (q->seq[i]=='G' or q->seq[i]=='g') p.push_back(3);
88                              if (q->seq[i]=='T' or q->seq[i]=='t') p.push_back(4);
89                      }
90
91                      std::vector<uint8_t> kmer(p.begin()+p.size()-k,p.end()); //is there a way to avoid making this copy?
92                      if (kmer_idx.find(kmer)!=kmer_idx.end() && kmer_idx_rev.find(kmer)!=kmer_idx_rev.end() && kmer_sites.find(kmer)!=kmer_sites.end()) {
93                        sa_intervals=kmer_idx[kmer];
94                        sa_intervals_rev=kmer_idx_rev[kmer];
95                        sites=kmer_sites[kmer];
(gdb) p p
$1 = std::vector of length 0, capacity 0
(gdb) p q.seq
$2 = 0x6905b0 'N' <repeats 76 times>

**Comment by rffrancon** [comment]
Reads which include non-DNA characters are now counted as "skipped".
@iqbal-lab is this the right solution for this problem?

**Comment by iqbal-lab** [comment]
Yes, no data in such a read.
