### ISSUE TITLE
Ubuntu 18.04 install woes

### ISSUE THREAD

**Issue by kdm9** [iqbal-lab-org/gramtools#163]
Hello Iqbal Lab folks!

I'm trying to get gramtools running on our Ubuntu 18.04 cluster, but having significant issues:

- install with the precompiled binaries fails, due to GLIBC/GLIBCXX version issues (18.04 glibc too old I assume)
- install from source fails, as the OS compiler toolchain is too old
- install from source within a conda env with updated dependencies and GCC/G++ fails, as cmake picks up the updated gcc but not the updated ar/ranlib, and conan doesn't even pick up the updated gcc. This leads to all sorts of fun errors during compilation.
- making a conda package fails, due to some strange linking error deep in conan-land. It seems like the cmake config hard-codes that conan is the source of the dependencies, which interferes with some conda dependencies and causes conflicting symbol names (e.g. regarding some zlib symbols in libhts.a). 
- Using docker/singularity isn't supported on our infrastructure, so i can't do that.

Is there any approach I'm missing? Is there any chance gramtools can move to HBB, or similar static compilation toolchains as discussed in the [original "static binaries" issue](https://github.com/iqbal-lab-org/gramtools/issues/101#issuecomment-769250966)?

Best,
Kevin

**Comment by bricoletc** [comment]
Hi Kevin,

Thanks for raising this, and for logging everything you've tried. I will look into both compiling against older libc/something else than libc (musl) and making a bioconda package. Will update situation here!

**Comment by bricoletc** [comment]
Hi @kdm9 , could you try the latest release, v1.9.0? 

I tried it in a Ubuntu 18.04 docker image and looks like it works :)

**Comment by kdm9** [comment]
Sorry, I forgot to say: this works perfectly on 18.04 now. Many thanks Brice!
