### ISSUE TITLE
gramtools gramtools backend expected at: /home/tools/anaconda3/lib/python3.7/site-packages/gramtools/bin/gram but not found

### ISSUE THREAD

**Issue by kdyoung100** [iqbal-lab-org/gramtools#168]
gramtools
gramtools backend expected at: /home/tools/anaconda3/lib/python3.7/site-packages/gramtools/bin/gram but not found

i don't know...

**Comment by kdyoung100** [comment]
gramtools discover
usage: gramtools discover [-h] [options] 

To run discovery, you need the following:
    - 'pip install py-cortex-api==2.2.0'
    - R and perl on your $PATH
        
gramtools discover: error: the following arguments are required: -i/--genotype_dir, -o/--discovery_dir
root@Zeta:/home/tools/anaconda3/lib/python3.7/site-packages/gramtools# gramtools -h
usage: gramtools [-h] [--version] {build, genotype, discover, simulate} ...

optional arguments:
  -h, --help            show this help message and exit
  --version

subcommands:
  {build, genotype, discover, simulate}
root@Zeta:/home/tools/anaconda3/lib/python3.7/site-packages/gramtools# gramtools --version
gramtools backend expected at: /home/tools/anaconda3/lib/python3.7/site-packages/gramtools/bin/gram but not found 

why...?

**Comment by iqbal-lab** [comment]
Can you please explain in detail how you installed gramtools,  and on what operating system?
