### ISSUE TITLE
make[1]: *** [CMakeFiles/Makefile2:260: libgramtools/CMakeFiles/gram.dir/rule] Error 2 make: *** [Makefile:186: gram] Error 2

### ISSUE THREAD

**Issue by joybio** [iqbal-lab-org/gramtools#169]
make[1]: *** [CMakeFiles/Makefile2:260: libgramtools/CMakeFiles/gram.dir/rule] Error 2
make: *** [Makefile:186: gram] Error 2

**Comment by bricoletc** [comment]
Hi, can you paste what commands you ran to (presumably) install gramtools?

**Comment by joybio** [comment]
conda create -n minos python=3.9
pip install conan
bash ./gramtools/build.sh

p.s. All dependencies in setup.cfg is ok.

**Comment by bricoletc** [comment]
what did `pip install ./gramtools-"${VERSION}"` give you? (replace VERSION) by the one you're installing)

**Comment by joybio** [comment]
version 1.10

**Comment by bricoletc** [comment]
Sorry, you're not providing me with enough info here.

**Comment by joybio** [comment]
Thanks. I have figured it out.
