### ISSUE TITLE
kmers in ref

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#17]
Do we really need the kmers_in_ref hash? is kmers_in_ref[kmer] not equivalent with kmers_sites[kmer].empty() ?

**Comment by iqbal-lab** [comment]
If you look at how kmers_in_ref is set, it's not really telling you if the kmer is in the ref. 
It is set iff the kmer does not overlap a number.

A kmer entirely enclosed in an allele will satisfy that criterion.

So it's not equivalent to kmers_sites[kmer].empty()

It may still be true that we don't need it, not sure.

**Comment by sm0179** [comment]
true. kmers_in_ref is a hash from kmer to the value of first_del at the end of the kmer search. We need it because we need to pass first_del as a parameter when we call bidir_search_bwd to continue the search after the kmer
