### ISSUE TITLE
Getting rid of some excess output args

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#20]
Why don't we just specify an output directory, and have fixed filenames for certain output files? Means you have less args to pass in.

**Comment by iqbal-lab** [comment]
+1

**Comment by rffrancon** [comment]
The experiment runner script does just that. Consistent file names across runs. But, I agree, the gramtools binary should also have that property.

**Comment by rffrancon** [comment]
This work as been finished.
