### ISSUE TITLE
Periodic assertion failures in SDSL

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#29]
eg here:

bash-4.1$ ./slow_unittest_bidir_search_bwd_fwd
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from BackwardSearchTest
[ RUN      ] BackwardSearchTest.NoVariantsSlowTest2
slow_unittest_bidir_search_bwd_fwd: /home/sm0179/include/sdsl/int_vector.hpp:1235: sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) [with unsigned char t_width = 0u; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_referencesdsl::int_vector<0u >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx < this->size()' failed.

I also saw this in the fast tests, and it went away when I fixed some errors in the input pRG/masks.
I can't see any problem with the input file, and on rerunning I can't reproduce this

**Comment by rffrancon** [comment]
I haven't seen these unit tests fail in a long time.
