### ISSUE TITLE
Add toy data to allow new user try out the code

### ISSUE THREAD

**Issue by jeromekelleher** [iqbal-lab-org/gramtools#36]
It would be useful to have some tiny data included in the distribution to allow a new user to try out the code. E.g., this

```
perl utils/vcf_to_linear_prg.pl --outfile my_species.prg --vcf big.vcf --ref reference.fa
```

would refer to some small VCF and reference included in the git repo.

**Comment by iqbal-lab** [comment]
Ah, that is already in utils / test but needs to be advertised and improved

**Comment by iqbal-lab** [comment]
That was meant to be "i agree we need to do this", not "yeah yeah, we've done it "

**Comment by jeromekelleher** [comment]
No worries, I had gone with the first interpretation!
