### ISSUE TITLE
Typo - festa

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#38]
We seem to have a lot of files containing "festa" - I guess typo for fasta ?
You might replace with fastaq to signify taking either fasta or fastq?

**Comment by rffrancon** [comment]
Solved in this branch: https://github.com/iqbal-lab-org/gramtools/tree/refactor_bidir_bwd

Will close issue after merge into dev.

**Comment by rffrancon** [comment]
Fixed on all branches.
