### ISSUE TITLE
coverages obtained with bitmask branch on joint DBLMSP prg

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#39]
Coverages obtained by running gramtools from bitmask branch on the 5 pf3k validation samples with the PRG built from the 2 DBLMSP genes are different from the ones obtained with master (previous pf3k analysis), dev and ranks.

cmd on aws: parallel --gnu -a /data1/gramtools_test_data/input/validation_samples './gramtools -p /data1/gramtools_test_data/input/final_joint_prg/updated_graph_gn01/Chr10_div_in_msp34_prg.in -c /data1/gramtools_test_data/input/final_joint_prg/updated_graph_gn01/csa_file -i /data1/gramtools_test_data/input/fastq/{}.fq.trim.gz -s /data1/gramtools_test_data/input/final_joint_prg/updated_graph_gn01/Mask_sites -a /data1/gramtools_test_data/input/final_joint_prg/updated_graph_gn01/Mask_alleles -v /data1/gramtools_test_data/output/test_bitmask/{}/Coverages -r /data1/gramtools_test_data/output/test_bitmask/{}/Reads_processed -b /data1/gramtools_test_data/output/test_bitmask/{}/int_al_file_bv -l /data1/gramtools_test_data/output/test_bitmask/{}/csa_memory -k 9 -f /data1/gramtools_test_data/input/final_joint_prg/updated_graph_gn01/precalc-kmers/kmersandrev > /data1/gramtools_test_data/output/test_bitmask/{}/out'

examples attached for sample 7G8 (for other samples, see /data1/gramtools_test_data/output/test_bitmask/ and /data1/gramtools_test_data/output/validation_samples/ on aws)
[Coverages_bitmask.txt](https://github.com/iqbal-lab-org/gramtools/files/1091712/Coverages_bitmask.txt)
[Coverages_master.txt](https://github.com/iqbal-lab-org/gramtools/files/1091722/Coverages_master.txt)

Coverages obtained by running gramtools on the whole-genome simulation are identical between the 4 branches

**Comment by sm0179** [comment]
this is due to what we already discussed about results returned by the bitmask search needing to be sorted by variant marker

**Comment by rffrancon** [comment]
No longer relevant. Branches no longer exist.
