### ISSUE TITLE
Move kmers indexing to build step

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#40]
At the moment, if the .precalc file is not found, the SA-intervals for small kmers are precalculated at the beginning of mapping. Better to move this step as part of the --build process, as it only needs to be done once

**Comment by rffrancon** [comment]
Solved with this commit: https://github.com/iqbal-lab-org/gramtools/commit/858160cdebd3f827c06335476ea69cb6491328ba
