### ISSUE TITLE
Add tests to linear PRG construction script

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#45]
need more tests for the linear PRG construction script. Should check if site markers appear in increasing order, if even numbers are always enclosed by 2 odds and if there are exactly 2 occurences of each odd marker

**Comment by rffrancon** [comment]
I think this script should be re-written in C++ (with tests of course).

**Comment by iqbal-lab** [comment]
Yes

**Comment by rffrancon** [comment]
Martin has done some work on this issue (pull request accepted). More to do but will start a new issue based around rewriting the PRG script.
