### ISSUE TITLE
Add size equal asserts for: linear PRG, site mask, and allele mask

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#46]
add assertion that linear PRG, site mask and allele mask have the same size

**Comment by rffrancon** [comment]
Where should we add this insert?

**Comment by sm0179** [comment]
I guess after the masks are parsed? and before starting k-mer precalc/mapping, since the backward search won't work if any of these data structures are incomplete

**Comment by rffrancon** [comment]
We should also add error handling in case the assertions fail.
