### ISSUE TITLE
Faster/lower RAM kmer hash

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#47]
I don't know the exact RAM usage by our kmer hash, but for future reference, we could replace it with https://github.com/rob-p/BooM which is a minimal perfect hash map based on Rayan's BBhash - uses about 3bits per element apparently. So for human, if we want to store 13mers, we need to store  66 million kmers--->this would only take 25Mb

**Comment by rffrancon** [comment]
Closing in favor of duplicate: https://github.com/iqbal-lab-org/gramtools/issues/71
