### ISSUE TITLE
gramtools no longer compiles on refactor_bidir_bwd

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#48]
I get this

bash-4.1$ make
Scanning dependencies of target gram
make[2]: Warning: File `CMakeFiles/gram.dir/depend.make' has modification time 39 s in the future
[  4%] Building CXX object CMakeFiles/gram.dir/src/map.cpp.o
[  8%] Building CXX object CMakeFiles/gram.dir/src/kmers.cpp.o
[ 12%] Building CXX object CMakeFiles/gram.dir/src/bidir_search_bwd.cpp.o
[ 16%] Building CXX object CMakeFiles/gram.dir/src/bidir_search_fwd.cpp.o
[ 20%] Building CXX object CMakeFiles/gram.dir/src/skip.cpp.o
[ 25%] Building CXX object CMakeFiles/gram.dir/src/bidir_search.cpp.o
[ 29%] Building CXX object CMakeFiles/gram.dir/src/masks.cpp.o
[ 33%] Building CXX object CMakeFiles/gram.dir/src/fm_index.cpp.o
[ 37%] Building CXX object CMakeFiles/gram.dir/src/variants.cpp.o
[ 41%] Building CXX object CMakeFiles/gram.dir/src/ranks.cpp.o
Linking CXX static library libgram.a
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 41%] Built target gram
Scanning dependencies of target git_version_py
[ 41%] Built target git_version_py
Scanning dependencies of target git_version
[ 41%] Built target git_version
Scanning dependencies of target gramtools
make[2]: Warning: File `CMakeFiles/gramtools.dir/depend.make' has modification time 39 s in the future
[ 45%] Building CXX object CMakeFiles/gramtools.dir/src/main.cpp.o
In file included from /home/zam/dev/git/gramtools/src/main.cpp:11:0:
/home/zam/dev/git/gramtools/include/git_version/git_version.hpp:1:1: error: stray ‘\’ in program
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/gramtools.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/gramtools.dir/all] Error 2
make: *** [all] Error 2
bash-4.1$ 

Tried this yesterday after git pull, and today I deleted the entire dir and recloned - same issue

 git log | head -n 10
commit 0e07f66751b8d46192dafd3442d9526247ad438f
Author: Robyn Ffrancon <rffrancon@gmail.com>
Date:   Wed Jun 28 19:35:05 2017 +0100

    stdout stored in quasimap run report.json

**Comment by rffrancon** [comment]
From what I can tell, travis built and ran passing unit tests on this branch. Is your local system time accurate? Please see: https://stackoverflow.com/questions/3824500/compiling-c-on-remote-linux-machine-clock-skew-detected-warning

Please copy and past the contents of /home/zam/dev/git/gramtools/include/git_version/git_version.hpp

It might also help to know the versions of git, make, and cmake that you are using.

Thank you for raising an issue!

**Comment by iqbal-lab** [comment]
This is a new clone, hard to believe is a time issue.

const std::string latest_commit = "0e07f66751b8d46192dafd3442d9526247ad438f";\nconst std::string current_branch = "refactor_bidir_bwd";\nconst std::string commit_log = "*****0e07f66 - Robyn Ffrancon, 2 hours ago : stdout stored in quasimap run report.json *****d2c8630 - Robyn Ffrancon, 4 hours ago : Merge branch 'py_git_version' into refactor_bidir_bwd *****adfde0d - Robyn Ffrancon, 4 hours ago : Merge branch 'setup_travis' into py_git_version *****69bfdd2 - Robyn Ffrancon, 4 hours ago : Merge branch 'setup_travis' into refactor_bidir_bwd *****1359a11 - Robyn Ffrancon, 4 hours ago : turn off travis email notifications";

**Comment by rffrancon** [comment]
A possible fix has been implemented on this branch: fix_git_version
Please try and build from that branch.

**Comment by iqbal-lab** [comment]
Works for me!

**Comment by rffrancon** [comment]
Implemented fix on all branches.
