### ISSUE TITLE
Change --reference argument to --fastaq

### ISSUE THREAD

**Issue by rffrancon** [iqbal-lab-org/gramtools#51]
This applies to both `--build` and `--quasimap` functionality.

**Comment by iqbal-lab** [comment]
No - --reference in build is correct.
build takes a reference fasta
quasimap takes a fastq from a sample

**Comment by rffrancon** [comment]
Bug fixed on all branches: https://github.com/iqbal-lab-org/gramtools/commit/259853d8545a3bb7cfa902cebe5c987196053291
