### ISSUE TITLE
variantkmers script error 

### ISSUE THREAD

**Issue by sm0179** [iqbal-lab-org/gramtools#54]
cmd: python3 /data1/apps/gramtools/utils/variantKmers.py -f ./prg_24Mb_human_chr21_with_44439_vars_based_on_restricted_ref/prg.fa -k 11 -n > ./prg_24Mb_human_chr21_with_44439_vars_based_on_restricted_ref/kmer/ksize_11.all

Traceback (most recent call last):
  File "/data1/apps/gramtools/utils/variantKmers.py", line 254, in <module>
    options.nreads, options.mask)
  File "/data1/apps/gramtools/utils/variantKmers.py", line 214, in exec
    for i in  bls.getKmerDict(ksize,nonvariant):
  File "/data1/apps/gramtools/utils/variantKmers.py", line 130, in getKmerDict
    j=c[i:i+k].tostring()
AttributeError: 'str' object has no attribute 'tostring'

tip of dev branch, commit 10ce3764c1d1c8746577e9e838acc2e97246f886

**Comment by iqbal-lab** [comment]
Python2 for script?

**Comment by sm0179** [comment]
I thought it's only supposed to work with python3

**Comment by iqbal-lab** [comment]
My guesses gramtools.py needs py3. VarKmers might need 2

**Comment by sm0179** [comment]
I get this with python2:
  File "/data1/apps/gramtools/utils/variantKmers.py", line 204
    def exec(fasta, ksize, nonvariant, nreads, mask, output_fpath=''):
           ^
SyntaxError: invalid syntax

**Comment by iqbal-lab** [comment]
Bah

**Comment by iqbal-lab** [comment]
literally python2? I've used 2.7 I think mostly

**Comment by rffrancon** [comment]
This issue should now be solved on all active branches.
