### ISSUE TITLE
variantKmers script is not pulling out all the right kmers

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#55]
Placeholder for meeting with @sm0179 and @rffrancon on Monday (at which point will modify this text).
Sorina spotted that this script is somehow missing kmers - as you increase k, we are finding fewer reads get mapped when using a .precalc file of kmers overlapping variants.

**Comment by sm0179** [comment]
this issue https://github.com/iqbal-lab-org/gramtools/issues/44 refers to the same thing

**Comment by iqbal-lab** [comment]
Ah yes, I see. The reason for this @rffrancon is that currently the exact mapper is v simple - is starts at the end of the read and keeps going. So if the end of the read does not overlap a variant, the kmer at the end of the read is not in the .precalc file/hash , and the quasimapper discards the read.

**Comment by iqbal-lab** [comment]
(An alternative solution is for the quasimapper to check all the kmers in the read, and discard the read if none of them are in the hash)

**Comment by sm0179** [comment]
yes, although that would mean slow quasimapping times for reads that end in k-mers that aren't in the hash

**Comment by iqbal-lab** [comment]
Yes, that's why I said it made more sense to add a few more kmers to the hash

**Comment by rffrancon** [comment]
Currently testing new implementation.

**Comment by rffrancon** [comment]
I've written tests for this feature. I think that it works correctly.
