### ISSUE TITLE
There is no matching destructor for csa's constructor - mem leak

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#7]
from valgrind

==55756== 688 bytes in 1 blocks are definitely lost in loss record 1 of 1
==55756==    at 0x4A09320: malloc (vg_replace_malloc.c:263)
==55756==    by 0x40DA4C: csa_constr(std::string, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, char_, char_, char*, bool) (csa_construction.cpp:33)

**Comment by rffrancon** [comment]
This is no longer an issue.
