### ISSUE TITLE
Release 0.5 requirements

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#72]
- [x] 1) Build from VCF
- [ ] 2) Works for Release 0.5 datasets (https://github.com/iqbal-lab-org/gramtools/issues/74)
- [x] 3) Indexing kmers takes <2 days with 24 cores for Release 0.5 datasets
- [x] 4) Handle mapping of fwd and rev comp reads (naive sufficient)
- [x] 5) Outputs mosaic fasta and VCF at graph sites
- [ ] 6) Tube map support? (optional)
- [x] 7) Merge with master, update README

Item 2 is the biggest, as far as I can see. Item 5 is optional.

**Comment by rffrancon** [comment]
@iqbal-lab Can we close this issue?

**Comment by rffrancon** [comment]
@iqbal-lab I would like to close this issue. I've reorganized everything as a project. Is that ok with you?

**Comment by iqbal-lab** [comment]
Yep
