### ISSUE TITLE
Release 0.5 datasets

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#74]
### 1. _P. falciparum_ good whole genome PRG. 
Use the pf3k cortex calls + DBLMSPs PRG

### 2. TB good whole genome PRG
SNPs and small indels above frequency 0.01
Combine the VCFs of 500 _M. tuberculosis_ samples, genotype those 500 samples at the deduplicated site-list, get a single VCF, exclude SNP/indels below 1% frequency

## What do we want for these datasets?
- Benchmark build, quasimap and infer for a single realistic test fastq of real data

**Comment by iqbal-lab** [comment]
For the record, I think item 7 is least priority of these. I tried running it on version 0.5.0, last git commit 97b3a4.The PRG was constructed, and kmer indexing started, but asfter ~36 hours, having indexed 261 million out of 3.7 billion, it hit the LSF memory limit of 150Gb RAM.

**Comment by iqbal-lab** [comment]
I've removed some excess datasets from this list. For historical purposes those datasets were:

### 5. _S. cerevisiae_ (bakers yeast)
Take the 93 genomes here: http://genome.cshlp.org/content/25/5/762.full
and run Cortex on them (Martin can help)
The following paper is good background, see Fig 3 in particular to give a sense of how much variation we are ignoring with our model https://www.nature.com/ng/journal/v49/n6/full/ng.3847.html
Provides a set of 7 _S.cerevisiae_ whole genomes.

### 6. S. pombe (brewers yeast)
Get the 161 samples from http://www.nature.com/ng/journal/v47/n3/full/ng.3215.html , run Cortex on them and get a VCF from that.

### 7. Human with 1000g variants above freq 0.05

**Comment by rffrancon** [comment]
@iqbal-lab I would like to close this issue. I've reorganized everything as a project. Is that ok with you?

The project references this issue. Nothing is lost.

**Comment by iqbal-lab** [comment]
Ywp
