### ISSUE TITLE
Code is too slow - can I have a 50000x speedup please?

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#76]

**Comment by rffrancon** [comment]
No problemo!

**Comment by iqbal-lab** [comment]
So you stick to your previous speed timings? Great news

**Comment by rffrancon** [comment]
As far as I can tell, it's performing correctly on WG and Chr10. Had 100% coverage on simulated reads, the allele coverage output file looked reasonable, all tests pass.

**Comment by iqbal-lab** [comment]
"Previously, generating the kmer index for the wg dataset and kmers of size 15 took a total time of 14461894 seconds split over 3167 cores. After the rewrite, the kmer index for kmer size 15 is generated in 296 seconds on a single core."
Closing.

**Comment by sm0179** [comment]
Awesome news, thanks Robyn!

Sent from my iPhone

On 30 Oct 2017, at 11:51, Zamin Iqbal <notifications@github.com<mailto:notifications@github.com>> wrote:


"Previously, generating the kmer index for the wg dataset and kmers of size 15 took a total time of 14461894 seconds split over 3167 cores. After the rewrite, the kmer index for kmer size 15 is generated in 296 seconds on a single core."
Closing.
