### ISSUE TITLE
valgrind issues in parse_masks

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#8]
Running this command:

vBWT /data3/projects/pf3k/pilot_paper_analysis/prg-constr/new_format/Chr10_div_in_msp34_prg_letter_added_between_adj_sites.in csa_file /data3/projects/pf3k/pilot_paper_analysis/prg-constr/simulate_reads_from_alt_ref/sim_reads_from_alt.fq  /data3/projects/pf3k/pilot_paper_analysis/prg-constr/new_format/Mask_sites /data3/projects/pf3k/pilot_paper_analysis/prg-constr/new_format/Mask_alleles Coverages Reads_processed int_alphabet_file csa_memory 9 /data3/projects/gramtools/wabi/precalc-kmers/kmersandrev

on Carlos' dev branch, through valgrind, we get a lot of errors.
Without valgrind, we segfault, and I'm not debugging that til the valgrind errors are fixed.

Run valgrind thus:

valgrind --leak-check=yes  <above command>

I'm documenting a lot of detail here, might be useful for Sorina

We see:

First some stuff which is due to htslib - you can ignore this

==3352== Conditional jump or move depends on uninitialised value(s)
==3352==    at 0x3A11A17546: index (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A06237: expand_dynamic_string_token (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A082F1: _dl_map_object (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A016DD: map_doit (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A0E265: _dl_catch_error (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A015F6: do_preload (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A0480E: dl_main (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A15B4D: _dl_sysdep_start (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A014A3: _dl_start (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A00B07: ??? (in /lib64/ld-2.12.so)
==3352==    by 0xB: ???
==3352==    by 0xFFEFFEDEE: ???
==3352== 
==3352== Conditional jump or move depends on uninitialised value(s)
==3352==    at 0x3A11A1754B: index (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A06237: expand_dynamic_string_token (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A082F1: _dl_map_object (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A016DD: map_doit (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A0E265: _dl_catch_error (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A015F6: do_preload (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A0480E: dl_main (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A15B4D: _dl_sysdep_start (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A014A3: _dl_start (in /lib64/ld-2.12.so)
==3352==    by 0x3A11A00B07: ??? (in /lib64/ld-2.12.so)
==3352==    by 0xB: ???
==3352==    by 0xFFEFFEDEE: ???
==3352== 

First error:

---

Mon Apr 25 22:32:27 2016
==3352== Invalid read of size 8
==3352==    at 0x40B500: std::vector<int, std::allocator<int> >::capacity() const (stl_vector.h:707)
==3352==    by 0x4175AC: std::vector<int, std::allocator<int> >::_M_fill_assign(unsigned long, int const&) (vector.tcc:219)
==3352==    by 0x417120: void std::vector<int, std::allocator<int> >::_M_assign_dispatch<int>(int, int, std::__true_type) (stl_vector.h:1207)
==3352==    by 0x416BFF: void std::vector<int, std::allocator<int> >::assign<int>(int, int) (stl_vector.h:488)
==3352==    by 0x41691D: parse_masks(std::vector<unsigned long, std::allocator<unsigned long> >&, std::vector<int, std::allocator<int> >&, std::string, std::string, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&) (parse_masks.cpp:37)
==3352==    by 0x440321: main (map.cpp:51)
==3352==  Address 0x56c3840 is 1,472 bytes inside a block of size 1,536 free'd
==3352==    at 0x4A07373: operator delete(void_) (vg_replace_malloc.c:457)
==3352==    by 0x4178AB: __gnu_cxx::new_allocator<std::vector<int, std::allocator<int> > >::deallocate(std::vector<int, std::allocator<int> >_, unsigned long) (new_allocator.h:100)
==3352==    by 0x417347: std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_M_deallocate(std::vector<int, std::allocator<int> >*, unsigned long) (stl_vector.h:175)
==3352==    by 0x416DE4: void std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_M_emplace_back_aux<std::vector<int, std::allocator<int> > const&>(std::vector<int, std::allocator<int> > const&&&) (vector.tcc:428)
==3352==    by 0x416B1C: std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::push_back(std::vector<int, std::allocator<int> > const&) (stl_vector.h:891)
==3352==    by 0x416850: parse_masks(std::vector<unsigned long, std::allocator<unsigned long> >&, std::vector<int, std::allocator<int> >&, std::string, std::string, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&) (parse_masks.cpp:24)
==3352==    by 0x440321: main (map.cpp:51)
==3352== 

OK, what is on  line 24 of parse_masks?

  std::ifstream h1(sites_fname);
  std::ifstream h2(alleles_fname);
  std::vector<int> v;

  no_sites=0;
  while (h1>>d)
    {
      if (d>no_sites) {
        no_sites=d;
        covgs.push_back(v);  <<<<<<<<<< this line
      }
      mask_s.push_back(d);
    }
  h1.close();

where covgs is passed in by reference as an argument of that function

 std::vectorstd::vector<int>& covgs

and what about line 37 (see above)

covgs[mask_s[i]-6].assign(no_alleles,0); //should have -5? might change anyway if I don't end up using mask_s 

Why are we subtracting 6 btw?

Anyway, 

..lots of that error. 

Then:

Reading KMERS...
DONE!

---

Mon Apr 25 22:41:07 2016
==3352== Use of uninitialised value of size 8
==3352==    at 0x438E7C: sdsl::rank_support_v5<(unsigned char)1, (unsigned char)1>::rank(unsigned long) const (rank_support_v5.hpp:123)
==3352==    by 0x438FB9: sdsl::rank_support_v5<(unsigned char)1, (unsigned char)1>::operator()(unsigned long) const (rank_support_v5.hpp:136)
==3352==    by 0x407297: std::tuple<unsigned long, unsigned long, unsigned long> sdsl::wt_int<sdsl::int_vector<(unsigned char)1>, sdsl::rank_support_v5<(unsigned char)1, (unsigned ch
ar)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >::lex_count<std::tuple<unsigned long, unsigned long
, unsigned long> >(unsigned long, unsigned long, unsigned long) const (wt_int.hpp:551)
==3352==    by 0x406945: bidir_search(sdsl::csa_wt<sdsl::wt_int<sdsl::int_vector<(unsigned char)1>, sdsl::rank_support_v5<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mc
l<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, 2u, 2u, sdsl::sa_order_sa_sampling<(unsigned char)0>, sdsl::isa_sampling<(unsig
ned char)0>, sdsl::int_alphabet<sdsl::sd_vector<sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned c
har)0, (unsigned char)1> >, sdsl::rank_support_sd<(unsigned char)1, sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_sup
port_mcl<(unsigned char)0, (unsigned char)1> >, sdsl::select_support_sd<(unsigned char)1, sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned cha
r)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, sdsl::int_vector<(unsigned char)0> > >&, unsigned long&, unsigned long&, unsigned long&, unsigned long&, unsigne
d char) (bidir_search.cpp:43)
==3352==    by 0x409F53: bidir_search_bwd(sdsl::csa_wt<sdsl::wt_int<sdsl::int_vector<(unsigned char)1>, sdsl::rank_support_v5<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, 2u, 2u, sdsl::sa_order_sa_sampling<(unsigned char)0>, sdsl::isa_sampling<(unsigned char)0>, sdsl::int_alphabet<sdsl::sd_vector<sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, sdsl::rank_support_sd<(unsigned char)1, sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, sdsl::select_support_sd<(unsigned char)1, sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >, sdsl::int_vector<(unsigned char)0> > >&, unsigned long, unsigned long, unsigned long, unsigned long, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, std::list<std::pair<unsigned long, unsigned long>, std::allocator<std::pair<unsigned long, unsigned long> > >&, std::list<std::pair<unsigned long, unsigned long>, std::allocator<std::pair<unsigned long, unsigned long> > >&, std::list<std::vector<std::pair<unsigned int, std::vector<int, std::allocator<int> > >, std::allocator<std::pair<unsigned int, std::vector<int, std::allocator<int> > > > >, std::allocator<std::vector<std::pair<unsigned int, std::vector<int, std::allocator<int> > >, std::allocator<std::pair<unsigned int, std::vector<int, std::allocator<int> > > > > > >&, std::vector<int, std::allocator<int> >&, unsigned long, bool&) (bidir_search_bwd.cpp:143)
==3352==    by 0x440B60: main (map.cpp:101)
==3352== 

which takes us to lex_count, as Sorina found also.

OK bug raised for now, am looking into it

**Comment by rffrancon** [comment]
I think this issue has been solved.
