### ISSUE TITLE
quasimap: allow >=1 reads file(s) as input

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/gramtools#83]
Allow input of more than one reads file. Most common use case is user has 2 FASTQ files to use as input.

**Comment by rffrancon** [comment]
This feature has been implemented with commit: b6a07409f05fa5cbfc33f12192574da09b6e36ee

Examples:
1) `gramtools quasimap --gram-directory ./gram --reads ./reads --reads ./reads_2`
2)  `gramtools quasimap --gram-directory ./gram --reads=./reads --reads=./reads_2`
3)  `gramtools quasimap --gram-directory ./gram --reads=./reads --reads=./reads_2 --reads=./reads_3`
