### ISSUE TITLE
Long pause prior to quasimapping

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/gramtools#86]
As a test, I'm quasimapping 100,000 human reads to the 1000g-5percent PRG.
I started the process one hour ago, and so far no output.

**Comment by rffrancon** [comment]
Are you using `--debug`? What is the full command that you're executing?

**Comment by iqbal-lab** [comment]
Might as well close this - after the long pause, it crashed as documented here: https://github.com/iqbal-lab-org/gramtools/issues/87
