### ISSUE TITLE
Build command optionally skips building PRG

### ISSUE THREAD

**Issue by rffrancon** [iqbal-lab-org/gramtools#95]
In some instances, gramtools should not be responsible for building the linear PRG. Instead, a pre-built linear PRG should be provided to the gramtools build command.

The build command will still need to run because gramtools needs an opportunity to build other supporting data structures (such as masks).

Example command:
`gramtools build --gram-directory ./gram --prg ./prg`

**Comment by iqbal-lab** [comment]
this would be awesome, as I have an initial MHC PRG to try out.

**Comment by rffrancon** [comment]
Merged into master here: d8a3082a921579e65081fa1932c42c4f2fb7953a
