### ISSUE TITLE
Non-root could use pip3 --user install ?

### ISSUE THREAD

**Issue by tseemann** [iqbal-lab-org/gramtools#98]
I think the `--user` option could work for people with root admin.
It puts it into `$HOME/.local/bin`

**Comment by rffrancon** [comment]
Thank you for your input! That's a good idea. I was worried that `--user` may not work as expected on the EBI cluster. But it seems to be working correctly. I'll simplify the recommended pip3 command in the readme.

**Comment by tseemann** [comment]
You can try it on a VM on EMBASSY ;-P
